version: '3'
services:
  arkxos-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: arkxos-mysql
    image: arkxos-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  arkxos-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: arkxos-redis
    hostname: arkxos-redis
    networks:
      - spring_cloud_default

  arkxos-register:
    build:
      context: ./arkxos-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
    container_name: arkxos-register
    hostname: arkxos-register
    image: arkxos-register
    networks:
      - spring_cloud_default

  arkxos-gateway:
    build:
      context: ./arkxos-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: arkxos-gateway
    hostname: arkxos-gateway
    image: arkxos-gateway
    networks:
      - spring_cloud_default

  arkxos-auth:
    build:
      context: ./arkxos-auth
    restart: always
    container_name: arkxos-auth
    hostname: arkxos-auth
    image: arkxos-auth
    networks:
      - spring_cloud_default

  arkxos-upms:
    build:
      context: ./arkxos-upms/arkxos-system
    restart: always
    container_name: arkxos-upms
    hostname: arkxos-upms
    image: arkxos-upms
    networks:
      - spring_cloud_default

  arkxos-monitor:
    build:
      context: ./arkxos-visual/arkxos-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: arkxos-monitor
    hostname: arkxos-monitor
    image: arkxos-monitor
    networks:
      - spring_cloud_default

  arkxos-codegen:
    build:
      context: ./arkxos-visual/arkxos-codegen
    restart: always
    container_name: arkxos-codegen
    hostname: arkxos-codegen
    image: arkxos-codegen
    networks:
      - spring_cloud_default

  arkxos-quartz:
    build:
      context: ./arkxos-visual/arkxos-quartz
    restart: always
    image: arkxos-quartz
    container_name: arkxos-quartz
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
