version: '3'
services:
  rapidark-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: rapidark-mysql
    image: rapidark-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  rapidark-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: rapidark-redis
    hostname: rapidark-redis
    networks:
      - spring_cloud_default

  rapidark-register:
    build:
      context: ./rapidark-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
    container_name: rapidark-register
    hostname: rapidark-register
    image: rapidark-register
    networks:
      - spring_cloud_default

  rapidark-gateway:
    build:
      context: ./rapidark-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: rapidark-gateway
    hostname: rapidark-gateway
    image: rapidark-gateway
    networks:
      - spring_cloud_default

  rapidark-auth:
    build:
      context: ./rapidark-auth
    restart: always
    container_name: rapidark-auth
    hostname: rapidark-auth
    image: rapidark-auth
    networks:
      - spring_cloud_default

  rapidark-upms:
    build:
      context: ./rapidark-upms/rapidark-upms-biz
    restart: always
    container_name: rapidark-upms
    hostname: rapidark-upms
    image: rapidark-upms
    networks:
      - spring_cloud_default

  rapidark-monitor:
    build:
      context: ./rapidark-visual/rapidark-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: rapidark-monitor
    hostname: rapidark-monitor
    image: rapidark-monitor
    networks:
      - spring_cloud_default

  rapidark-codegen:
    build:
      context: ./rapidark-visual/rapidark-codegen
    restart: always
    container_name: rapidark-codegen
    hostname: rapidark-codegen
    image: rapidark-codegen
    networks:
      - spring_cloud_default

  rapidark-quartz:
    build:
      context: ./rapidark-visual/rapidark-quartz
    restart: always
    image: rapidark-quartz
    container_name: rapidark-quartz
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
