# 数据库访问配置
# 主数据源，默认的
spring:
  data:
  # redis连接配置
    redis:
      host: localhost
  #    port: 8379
      database: 0
      password: rapidark # Redis密码，没有留空
    redisson:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming:
        # 采用@Column注解字段命名，否则会用砣峰命名规则生产数据库字段名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/rapidark_cloud10_gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
  sqltoy:
    # 指定缓存翻译配置文件
    #translateConfig: classpath:/dataset/ltc/sqltoy-translate.xml
    # 这里要注意，指定sql文件的目录(是目录不是具体文件或文件匹配表达式),多个可以用逗号分隔，会自动向下寻找
    sqlResourcesDir: classpath:/dataset/gateway-manage
    # defaultDataSource: masterDataSource
    # 缓存翻译的配置
    #translateConfig: classpath:sqltoy-translate.xml
    # debug模式会打印执行sql
    debug: false
    # 提供统一字段:createBy createTime updateBy updateTime 等字段补漏性(为空时)赋值(可选配置)
    #unifyFieldsHandler: com.sqltoy.plugins.SqlToyUnifyFieldsHandler
    # sql执行超过多长时间则进行日志输出,用于监控哪些慢sql(可选配置:默认30秒)
    printSqlTimeoutMillis: 3000000